// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_design_layers_version.test.ts.

/** The version of the `@ggdna/dna-design-layers` package. */
export const dnaDesignLayersVersion = '0.2.0';
